/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author LegendarioP
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logadoUsuario3 = new javax.swing.JLabel();
        logadoUsuario = new javax.swing.JLabel();
        FundoUsuarioLogado = new javax.swing.JLabel();
        fundoMenuPrincipal = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();
        BarraMenu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuCadastroCliente = new javax.swing.JMenuItem();
        menuCadastroBarbeiro = new javax.swing.JMenuItem();
        menuCadastroServico = new javax.swing.JMenuItem();
        menuAgenda = new javax.swing.JMenu();
        menuAgendaAgendamento = new javax.swing.JMenuItem();
        menuOpcoes = new javax.swing.JMenu();
        MenuOpcoesSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logadoUsuario3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        logadoUsuario3.setForeground(new java.awt.Color(255, 255, 255));
        logadoUsuario3.setText("BEM-VINDO:");
        logadoUsuario3.setToolTipText("");
        getContentPane().add(logadoUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 120, -1, -1));

        logadoUsuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        logadoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        logadoUsuario.setText("Usuario");
        getContentPane().add(logadoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 150, -1, -1));

        FundoUsuarioLogado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo_1.png"))); // NOI18N
        getContentPane().add(FundoUsuarioLogado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 110, 420, 70));

        fundoMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/fundo-MenuPrincipal.jpg"))); // NOI18N
        getContentPane().add(fundoMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        desktop.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(desktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 850, 530));

        menuCadastro.setText("Cadastro");
        menuCadastro.setActionCommand("User");
        menuCadastro.setEnabled(false);
        menuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroActionPerformed(evt);
            }
        });

        menuCadastroCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/cliente-icon.png"))); // NOI18N
        menuCadastroCliente.setText("Cliente");
        menuCadastroCliente.setEnabled(false);
        menuCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroCliente);

        menuCadastroBarbeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/electric-razor.png"))); // NOI18N
        menuCadastroBarbeiro.setText("Barbeiro");
        menuCadastroBarbeiro.setEnabled(false);
        menuCadastroBarbeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroBarbeiroActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroBarbeiro);

        menuCadastroServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/tesoura-icon.png"))); // NOI18N
        menuCadastroServico.setText("Serviço");
        menuCadastroServico.setEnabled(false);
        menuCadastroServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroServicoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroServico);

        BarraMenu.add(menuCadastro);

        menuAgenda.setText("Agenda");

        menuAgendaAgendamento.setText("Agendamento");
        menuAgendaAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgendaAgendamentoActionPerformed(evt);
            }
        });
        menuAgenda.add(menuAgendaAgendamento);

        BarraMenu.add(menuAgenda);

        menuOpcoes.setText("Opções");

        MenuOpcoesSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenuOpcoesSair.setText("Sair");
        MenuOpcoesSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpcoesSairActionPerformed(evt);
            }
        });
        menuOpcoes.add(MenuOpcoesSair);

        BarraMenu.add(menuOpcoes);

        setJMenuBar(BarraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroServicoActionPerformed
        // TODO add your handling code here:
        TelaServico tlserv = new TelaServico();
        tlserv.setVisible(true);
        fundoMenuPrincipal.add(tlserv);
    }//GEN-LAST:event_menuCadastroServicoActionPerformed

    private void MenuOpcoesSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpcoesSairActionPerformed
        // COMANDO BOTAO SAIR
        int Sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?","Atenção" ,JOptionPane.YES_NO_OPTION);
        if(Sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_MenuOpcoesSairActionPerformed

    private void menuAgendaAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgendaAgendamentoActionPerformed
        // TODO add your handling code here:
        AgendaCadastro tlagend = new AgendaCadastro();
        tlagend.setVisible(true);
    }//GEN-LAST:event_menuAgendaAgendamentoActionPerformed

    private void menuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroClienteActionPerformed
        // TODO add your handling code here:
        TelaCliente tlcliente = new TelaCliente();
        tlcliente.setVisible(true);
        fundoMenuPrincipal.add(tlcliente);
    }//GEN-LAST:event_menuCadastroClienteActionPerformed

    private void menuCadastroBarbeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroBarbeiroActionPerformed
        // TODO add your handling code here:
        TelaBarbeiro tlbarber = new TelaBarbeiro();
        tlbarber.setVisible(true);
        fundoMenuPrincipal.add(tlbarber);
    }//GEN-LAST:event_menuCadastroBarbeiroActionPerformed

    private void menuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JLabel FundoUsuarioLogado;
    private javax.swing.JMenuItem MenuOpcoesSair;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel fundoMenuPrincipal;
    public static javax.swing.JLabel logadoUsuario;
    public static javax.swing.JLabel logadoUsuario3;
    private javax.swing.JMenu menuAgenda;
    private javax.swing.JMenuItem menuAgendaAgendamento;
    public static javax.swing.JMenu menuCadastro;
    public static javax.swing.JMenuItem menuCadastroBarbeiro;
    public static javax.swing.JMenuItem menuCadastroCliente;
    public static javax.swing.JMenuItem menuCadastroServico;
    private javax.swing.JMenu menuOpcoes;
    // End of variables declaration//GEN-END:variables
}
